# Generated by Django 5.1.6 on 2025-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='ticket_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
