# Generated by Django 5.1.6 on 2025-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0002_museum_opening_hours_museum_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
